### ISSUE TITLE
SDK Crash in production

### ISSUE THREAD

**Issue by ubarua123** [truecaller/android-sdk-sample#3]
```
Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'java.lang.Integer android.telephony.PhoneStateListener.mSubId' on a null object reference
       at android.telephony.TelephonyManager.listen(TelephonyManager.java:5082)
       at com.truecaller.android.sdk.clients.VerificationClient.unRegisterIncomingCallReceiver(VerificationClient.java:218)
       at com.truecaller.android.sdk.clients.VerificationRequestManagerImpl.unRegisterIncomingCallListener(VerificationRequestManagerImpl.java:212)
       at com.truecaller.android.sdk.clients.callbacks.MissedCallInstallationCallback.notifyMissedCallVerifiedMaybe(MissedCallInstallationCallback.java:114)
       at com.truecaller.android.sdk.clients.callbacks.MissedCallInstallationCallback.onCallReceivedFrom(MissedCallInstallationCallback.java:100)
       at com.truecaller.android.sdk.clients.callVerification.IncomingCallListener.onCallStateChanged(IncomingCallListener.java:56)
       at android.telephony.PhoneStateListener$IPhoneStateListenerStub.lambda$onCallStateChanged$10(PhoneStateListener.java:1030)
       at android.telephony.-$$Lambda$PhoneStateListener$IPhoneStateListenerStub$6czWSGzxct0CXPVO54T0aq05qls.run(-.java:6)
```

Device type: POCO M3
Android: 10

**Comment by parth0907** [comment]
Hi @ubarua123 

Hope you are doing great! 

If you could share the information mentioned below, it would be really helpful to get this resolved : 

1. Truecaller App version 
2. If this is reproducible on any other device than "POCO M3" 
3. Exact steps to reproduce 
4. Truecaller SDK version 

Once you share the information mentioned above, we shall then open the investigation at our end. 


_Please feel free to reach out to us via our support channel https://developer.truecaller.com/support for a faster and dedicated response._

**Comment by ubarua123** [comment]
Hi @parth0907 

1. TrueCaller App version - Cannot determine that obviously since it's on production.
2. Devices reproduced on - `POCO M3, Redmi Note 9 Pro`
3. Exact steps to reproduce - Cannot specify as it occurred in production. Saw this log -> `[onRequestFailure] ==> failed to connect to api4.truecaller.com/35.190.118.8 (port 443) from /25.70.221.221 (port 41250) after 10000ms` print 4 times. I suppose the user was facing internet issues.
4. TrueCaller SDK version - `2.6.0`

**Comment by parth0907** [comment]
What is the frequency of this crash on your production environment? @ubarua123
